language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t imismailkhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imismailkhan/react-test npm run test -- --coverage

after_success:
  - docker build -t imismailkhan/multi-client ./client
  - docker build -t imismailkhan/multi-nginx ./nginx
  - docker build -t imismailkhan/multi-server ./server
  - docker build -t imismailkhan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push imismailkhan/multi-client
  - docker push imismailkhan/multi-nginx
  - docker push imismailkhan/multi-server
  - docker push imismailkhan/multi-worker